sudo: required

services:
  - docker

before_install:
  - docker pull lorenzb/proveth@sha256:243f6a6ef2b90c636f29eb384214a2471a567bd7943d1eb32f47629fe12ccdeb

script:
  - ls
  - pwd
  - docker run -v $PWD:/repo lorenzb/proveth@sha256:243f6a6ef2b90c636f29eb384214a2471a567bd7943d1eb32f47629fe12ccdeb bash -c "cp -r /repo /repo2  && cd /repo2/ && python3.6 -m pip install -r requirements.txt && python3.6 onchain/test/test_ProvethVerifier.py"
